# Generated by Django 6.0.7 on 2026-07-07 18:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('compliance', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('evidence_type', models.CharField(choices=[('document', 'Document'), ('link', 'Link'), ('screenshot', 'Screenshot'), ('report', 'Report'), ('other', 'Other')], default='link', max_length=50)),
                ('storage_backend', models.CharField(choices=[('external_url', 'External URL'), ('local', 'Local'), ('s3', 'S3')], default='external_url', max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('checksum', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='active', max_length=30)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization__name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='assessments.assessmentanswer')),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='compliance.control')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='evidence.evidence')),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='compliance.risk')),
            ],
            options={
                'ordering': ['evidence__title', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('assessment_answer__isnull', True), ('control__isnull', True), ('risk__isnull', False)), models.Q(('assessment_answer__isnull', True), ('control__isnull', False), ('risk__isnull', True)), models.Q(('assessment_answer__isnull', False), ('control__isnull', True), ('risk__isnull', True)), _connector='OR'), name='evidence_link_has_exactly_one_target')],
            },
        ),
    ]
