# Generated by Django 6.0.7 on 2026-07-08 01:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assets', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAssetOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsibility', models.CharField(choices=[('business_owner', 'Business owner'), ('technical_owner', 'Technical owner'), ('privacy_owner', 'Privacy owner'), ('security_owner', 'Security owner')], default='business_owner', max_length=50)),
                ('ai_use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_owners', to='ai_assets.aiusecase')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_asset_ownerships', to='organizations.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_asset_owners', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__name', 'ai_use_case__name', 'responsibility'],
                'constraints': [models.UniqueConstraint(fields=('ai_use_case', 'membership', 'responsibility'), name='unique_ai_asset_owner_responsibility')],
            },
        ),
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('provider_model_id', models.CharField(blank=True, max_length=255)),
                ('model_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('multimodal', 'Multimodal'), ('embedding', 'Embedding'), ('other', 'Other')], default='text', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_review', 'Under review'), ('deprecated', 'Deprecated'), ('retired', 'Retired')], default='active', max_length=30)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=30)),
                ('ai_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_models', to='ai_assets.aitool')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_models', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_ai_model_name_per_organization')],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('database', 'Database'), ('document', 'Document'), ('api', 'API'), ('user_input', 'User input'), ('log', 'Log'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('data_classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='internal', max_length=50)),
                ('contains_personal_data', models.BooleanField(default=False)),
                ('contains_sensitive_data', models.BooleanField(default=False)),
                ('ai_use_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sources', to='ai_assets.aiusecase')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_data_source_name_per_organization')],
            },
        ),
    ]
