# Generated by Django 6.0.7 on 2026-07-07 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('integer', 'Integer'), ('decimal', 'Decimal'), ('percentage', 'Percentage'), ('currency', 'Currency')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('retired', 'Retired')], default='active', max_length=30)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_key', models.CharField(max_length=100)),
                ('target_table', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('warning', 'Warning'), ('error', 'Error')], max_length=30)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('executed_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-executed_at', 'check_key'],
                'indexes': [models.Index(fields=['check_key', 'executed_at'], name='analytics_d_check_k_4f8df5_idx'), models.Index(fields=['target_table', 'status'], name='analytics_d_target__dce45b_idx')],
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows_read', models.PositiveIntegerField(default=0)),
                ('rows_written', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at', 'source_name'],
                'indexes': [models.Index(fields=['source_name', 'started_at'], name='analytics_i_source__43bc69_idx'), models.Index(fields=['status'], name='analytics_i_status_c69184_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('computed_at', models.DateTimeField()),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='analytics.metricdefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__name', 'metric_definition__key', '-computed_at'],
                'indexes': [models.Index(fields=['organization', 'computed_at'], name='analytics_m_organiz_bd0edf_idx'), models.Index(fields=['metric_definition', 'period_start', 'period_end'], name='analytics_m_metric__f700a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'metric_definition', 'period_start', 'period_end'), name='unique_metric_snapshot_period')],
            },
        ),
    ]
